### PR TITLE
Support tsv file

### PR DESCRIPTION
**Pull request by d8660091**
**Description of changes**

**Type of Change**

- [ ] Bug
- [ ] Styling
- [ ] New Feature

**Checklist before requesting review:**

- [ ] Matches design:

  - component sizes, spacing, and styles
  - font size, weight, colour
  - spelling has been double checked

- [ ] New uikit components have Storybook stories
- [ ] Feature is minimally responsive.
- [ ] Manual testing of UI feature.
- [ ] Selenium test is completed and passing.

### CODE REVIEW

**Comment by joneubank** [comment]
What motivated this change? the template name should be provided without `.tsv`, if it isn't that feels like an oddity in the UI.  Do we intentionally want to support making `/template/registration` and `/template/registration.tsv`both valid paths?

**Comment by d8660091** [comment]
@joneubank The default file name is [name] if we download a file from a link `/template/[name]`. If we use `/template/registration`. The file name would be `registration`. So to make the file name have a `.tsv` suffix. I made the change

**Comment by joneubank** [comment]
Ok that makes sense. Thanks!

**Comment by d8660091** [comment]
Thanks

**Pull request merged**
